### ISSUE TITLE
Tabs look disconnected from the editor window

### ISSUE THREAD

**Issue by sfrench87** [liviuschera/noctis#15]
![tabs](https://user-images.githubusercontent.com/48254143/56998341-dc83a600-6ba2-11e9-8009-dc185f8385d6.JPG)
Very minor issue but it started to bug me as the tabs look like they are floating and not attached to the editor window.

**Comment by liviuschera** [comment]
Hey Paul,

Thanks for your interest in the theme. I'll have a look into it as soon as possible.

Cheers!

**Comment by liviuschera** [comment]
It should be fixed in v7.28.0
