### ISSUE TITLE
Quick fixes indicator shown twice

### ISSUE THREAD

**Issue by sfrench87** [liviuschera/noctis#16]
![code_actions](https://user-images.githubusercontent.com/48254143/57030734-ac3d1580-6c3d-11e9-8919-51ed48985a10.JPG)

It doesn't happen with other themes i tested and i could find a fix for it myself.

**Comment by sfrench87** [comment]
Found it, its "editorHint.border", making that the same as the editor background fixed it for me.

**Comment by sfrench87** [comment]
Sorry for this :) I also noticed a small gap on the diff editor on any insertion or delection when you highlight that line. Reading through the vscode theme guide i noticed it says to only use a border or a background highlight, i removed the border and it was fixed.

**Comment by liviuschera** [comment]
Nice catch mate. I'll fix it ASAP. Thanks for the providing the solutions as well.

**Comment by liviuschera** [comment]
It should be fixed in v7.28.1
Cheers!
