### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by deandex** [liviuschera/noctis#17]
I love this theme very much, but get one issue after install it. I can't set Noctis theme, file not found, i think because the file name with uppercase. After rename it from Noctis.json to noctis.json, now i can use it. 

Thank you if this issue fixed on next update

**Comment by liviuschera** [comment]
Thank you for your kind words, mate! I'm happy you like the the theme and spending your time to make it better. 
The issue should be fixed in v8.2.0. Let me know if it works for you.

Cheers!
