### ISSUE TITLE
White bottom border in hovered focused tab

### ISSUE THREAD

**Issue by youknowznm** [liviuschera/noctis#18]
Firstly thanks so much for such a great theme, best vscode theme I've ever used. Uninstalled all others already. 👍👍👍

Thing is, in light Noctis themes(Lux and Hibernus), when current focused tab is hovered,  a 1px #fff border appears on the bottom of it.

![hovered_focused_tab_style](https://user-images.githubusercontent.com/11565755/57436814-17589e80-7273-11e9-8bb0-96ad6d2cb3da.png)

It felt a little, little bit mismatching to me, and I didn't found similar border in dark Nocits themes. (If I'm to pick a tiny, tiny flaw from the epic theme, this would be it.) 🤔 Anyway, I haven't got much UI experience, probably it's by design? Please let me know. 😁

**Comment by liviuschera** [comment]
Hey there, Cinder! I'm thrilled that you like Noctis theme and thank you for your great feedback. 

You are right, the border should not be there. Good catch, mate! I have fixed the issue in v8.2.0. Please let me know if it's OK for you.

Cheers!
