### ISSUE TITLE
Support LaTeX

### ISSUE THREAD

**Issue by innerlee** [liviuschera/noctis#19]
This is a cute theme! Would be super great if LaTeX is on the language list

**Comment by liviuschera** [comment]
Thanks for the feedback and for the great suggestion. I'm glad that you are enjoying the theme. 

I will be looking into this request ASAP.

Cheers!

**Comment by liviuschera** [comment]
Done! Have fun! 🙂

**Comment by innerlee** [comment]
Cool! thanks!
