### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by justinHensley** [liviuschera/noctis#2]
Which font are you using in your preview images in README.md ?   Love the font almost as I love the theme!

**Comment by liviuschera** [comment]
I'm happy that you like it. 

The font in the screenshots are actually 2 fonts glued together with [Custom CSS](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css). For normal style I used [Hasklig](https://github.com/i-tu/Hasklig)  and for italics [Cartograph Mono CF](http://connary.com/cartograph.html).
I think there is a beautiful synergy between the two fonts and they intertwine naturally together.

I will add this bit of info in the README file.

**Comment by vishalbasnet23** [comment]
Hi,
I have installed both fonts but I still cannot see any changes to my current setup. Can you please let me know what I should be doing here?

Thank you in advance.

**Comment by liviuschera** [comment]
My pleasure.

The walkthrough is for a Windows OS. I assume that for Unix and MacOS you would have to change only the path.

1. IMPORTANT: _Run as aministrator_ VS Code
2. install [Custom CSS and JS Loader](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css)
3. download or copy the content of [customvscode.css](https://github.com/liviuschera/noctis/blob/master/vscodecustom.css)
4. copy the file in `Users\yourusername\customvscode.css`. This is what I have on my system `c:\Users\liviuschera\customvscode.css`
5. In `settings.json` add:
    ```json
      "editor.fontFamily": "Hasklig",
      "vscode_custom_css.imports":
        [
          "file://C:/Users/yourusername/vscodecustom.css"
        ],
    ```
6. press `F1`
7. Select `Enable Custom CSS and JS`
8. Reload VS Code (it doesn't have to be in administrator mode)



>NOTES:
>- if Code complains about that it is corrupted, simply click “Don't show again”.
>- make sure that you comment out the optional CSS code if you don't want to change the UI's default font.

Have fun! :)

**Comment by liviuschera** [comment]
Hi there!

Please make sure you have followed step 4 from my walk-through and let me know if it works.

Cheers!

**Comment by tuucan** [comment]
Hi, how do you enable the alternative lovercase 's' version of the font in Code?

**Comment by Jado99kc** [comment]
even after following all steps my fonts seem to be different than the one in the previews. :(

**Comment by rediffusion** [comment]
@Jado99kc 

 Hello, my friend. Try this:

3.  I used the font "[Cousine](https://pastebin.com/FS5ZVWMe)" cuz "Cartograph Mono CF" costs $40.
5.  In settings.json add:
```
    "editor.fontFamily": "Fira Code",
    "editor.fontLigatures": true,
    "vscode_custom_css.imports":
      [
        "file:\\C:\\Users\\YourUserName\\customvscode.css"
      ],
```
P.S. ••• Hasklig is none relevent font, I recomended to you use [Fira Code](https://github.com/tonsky/FiraCode/releases/tag/2), [PragmataPro](https://github.com/fabrizioschiavi/pragmatapro) or [iosevka](https://github.com/be5invis/Iosevka/releases/tag/v3.0.0-alpha.2) (these fonts supports 'ligatures').

 Cheers! ✌️👍

**Comment by commgina** [comment]
whats the font used in the comments ?

**Comment by rediffusion** [comment]
@commgina 

 I think it's [Cousine](https://www.1001fonts.com/cousine-font.html).

**Comment by ShadyTollipop** [comment]
Who wants paid fonts like Cartograph CF Mono and others for free??
