### ISSUE TITLE
Diff in source control have ugly border

### ISSUE THREAD

**Issue by qell** [liviuschera/noctis#20]
Hi. I use Noctis Uva. When run diff using Noctis I have ugly border by lines. Screenshot:
![image](https://user-images.githubusercontent.com/41490584/58018793-1857be80-7b04-11e9-8cc9-36d1d312d931.png)

I don't change any settings with UI and on other themes(for example built in themes) haven't this problem.

**Comment by liviuschera** [comment]
Hi there! 

Thanks for pointing out this issue. I'm on to it.

Cheers!

**Comment by liviuschera** [comment]
Done. Enjoy!
