### ISSUE TITLE
Improve Color Theme of Terminal

### ISSUE THREAD

**Issue by innerlee** [liviuschera/noctis#21]
![image](https://user-images.githubusercontent.com/9464825/58679154-e57bb900-8394-11e9-8845-db51748b1b36.png)

I love this theme. However the color matching for terminal is a little less harmonic. Above is a comparison: left noctis, right [nord](https://github.com/arcticicestudio/nord). Nord's terminal is better imho.

**Comment by liviuschera** [comment]
Hi there! Thanks for your feedback. 
Would you please elaborate as I'm not seeing the issue you want to point out?

Cheers!

**Comment by innerlee** [comment]
Hi, this color is too bright.

![image](https://user-images.githubusercontent.com/9464825/58687031-03f0ad00-83b3-11e9-8205-ef8c9e89c9ca.png)

**Comment by liviuschera** [comment]
Good catch, mate! It is, indeed, brighter than intended (65% luminosity instead of 60%). Is there anything else?

**Comment by innerlee** [comment]
Thanks! just personal feelings. Below, the three colors are also brighter than my expectation

![image](https://user-images.githubusercontent.com/9464825/58690225-9d23c180-83bb-11e9-9643-55026dc84473.png)

**Comment by innerlee** [comment]
For comparison, the following is the nord theme

![image](https://user-images.githubusercontent.com/9464825/58690343-ed028880-83bb-11e9-8304-21259337da01.png)

**Comment by liviuschera** [comment]
Done! Please give it a go an let me know how do you feel about it.

**Comment by innerlee** [comment]
It's definitely better now.

The background color with gray font is barely visible in the following places. Compare them with the datetime in the bottom-right corner. The datetime is clearer and less causes eye strains.

![image](https://user-images.githubusercontent.com/9464825/58702157-8f7c3500-83d7-11e9-9859-a13474c4298e.png)

**Comment by liviuschera** [comment]
Just to be clear, the screenshots are from Noctis Minumus?

**Comment by innerlee** [comment]
yea they are

**Comment by liviuschera** [comment]
I tweaked it a bit more. Give it a spin and let me know if it's better for you.

**Comment by innerlee** [comment]
Cool! looks good. See below.

![image](https://user-images.githubusercontent.com/9464825/58763568-d6605b00-858e-11e9-886d-d07f10162be1.png)
