### ISSUE TITLE
Italics in syntax highlighting

### ISSUE THREAD

**Issue by chiangs** [liviuschera/noctis#25]
I would really love more support for italics in the syntax highlighting similar to Lucy, where `const`, `import`, `using`, and params or types in params (typescript) are italicized. I have used Lucy for a bit, but I prefer Noctis Minimus.

Perhaps replace the bold parts with italicized...anyway, here's hoping for some more italics 🍻

Thanks!

**Comment by liviuschera** [comment]
Thanks for your suggestions mate. Let me look into it and I'll get back to you.

**Comment by liviuschera** [comment]
Done! Import/export statements and datatype annotations are italicized. Hope you'll like it.

Cheers!

**Comment by chiangs** [comment]
awesome! a little nit-picky, but perhaps consider extending the syntax highlighting to non primitive types?

Example of current, whereas visually I personally would expect all types to be formatted the same.

![code](https://user-images.githubusercontent.com/10984593/60789354-32ef0100-a15f-11e9-9ea5-2c89cd5a2e9e.png)

**Comment by liviuschera** [comment]
Thanks for your feedback mate, I'm glad that you like it. 

Although for the highlighting of the type annotations I'm already using a distinct colour I decided (as per your suggestion, which I really like 😊)  to italicise only the primitive data types to have a nice visual distinction between primitive types and non-primitive ones. In upcoming releases I will implement this change across all the languages that have primitive type annotations.

Cheers!

**Comment by chiangs** [comment]
Cool, I can also see the appeal of having it differentiated, cheers for being so quick to implement changes! 🍻
