### ISSUE TITLE
"Progressive"/"Alternating" Lighting for List Items in Markdown (request)

### ISSUE THREAD

**Issue by macintacos** [liviuschera/noctis#26]
Not sure if it's even possible in VSCode, but it'd be nice if there was a gradual saturation of color for a list item's text depending on how far a list item is nested in Markdown. Currently, the first-level item's color is the same as any other indentation level, which can make some of my markdown notes seem very...same-y.

For example, this:

```
- Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  - Donec ac nisi laoreet, vestibulum nulla a, condimentum enim.
  - Duis dignissim nulla in molestie maximus.
      - Nam aliquam odio vitae mauris feugiat, sit amet lacinia elit ullamcorper.
      - In tincidunt ipsum eu malesuada viverra.
  - Ut eleifend lectus id elit commodo, at lobortis ipsum feugiat.
  - Etiam sodales metus at consequat dignissim.
  - Etiam varius magna non finibus vulputate.
- Ut id enim ultrices, consequat turpis eu, vehicula augue.
- Donec commodo metus et dolor pharetra tristique.
- Proin venenatis erat laoreet, mollis justo in, auctor ipsum.
  - Phasellus eget urna facilisis, egestas tortor et, venenatis velit.
  - Nunc ut turpis dapibus, dapibus magna ac, blandit felis.
    - Mauris vulputate lorem eget scelerisque tincidunt.
      - Pellentesque id risus vestibulum, aliquam ligula et, lacinia tellus.
      - Vestibulum maximus massa sit amet nulla imperdiet, vel accumsan nulla ultrices.
```

Looks like this (in Noctis Obscuro):

![](https://cl.ly/15a8b9c99873/Image%202019-08-12%20at%2000.18.18.png)

While I could understand it if maybe some prefer for all of this text to look the same, I for one would love it if there was some kind of visual difference between indentation levels. Is it possible to either add some progressive saturation of list item text in markdown, or maybe have some alternating styling so that one can more clearly denote one line from another? I keep coming back to desaturation because I think it'd look pretty neat with the way I take notes now.

**Comment by liviuschera** [comment]
Hi mate!

This is what I got by playing with saturation:

![2019-08-13_13-11-49](https://user-images.githubusercontent.com/12068956/62913838-dd94b800-bdcc-11e9-9e54-5970445981e6.png)

1st level: `#e4b781`  (original color 65% saturation)
2nd: `#d5b690` (45% saturation)
3rd & 4th: `#c6b49f` (25% saturation) (unfortunately VSCode cannot distinguish them) 
5th: `##b6b3af` (5% saturation)

The way it looks right now I can barely tell the shades apart. 

What do you reckon?

**Comment by macintacos** [comment]
For me, I think that I'd like this change; I'm trying and failing to find any comparisons in other applications that could be used as a guide for what would be better than just changing syntax, and I'm not coming up with anything.

I'm not sure if you'd get into adding options to the extension, but if it could be an option I'd be happy with that (you can leave the default of no desaturation for those who aren't as picky as me 😬).

I'll leave it up to you though!

**Comment by liviuschera** [comment]
I think that for now I'll leave the highlighting as it is. Thanks for your input and the interest in making Noctis a better theme.

Cheers!
