### ISSUE TITLE
Improve Diff view coloring for Noctis Azureus

### ISSUE THREAD

**Issue by amithegde** [liviuschera/noctis#27]
Been using Noctis Azureus for a while and love the colors. I find that on the diff view colors are not so prominent and and not easy to identify changes. For example:

![image](https://user-images.githubusercontent.com/816051/63630315-54e8f980-c5ce-11e9-8fe9-a6586a8e9b48.png)

VS say monokai:
![image](https://user-images.githubusercontent.com/816051/63630345-911c5a00-c5ce-11e9-84db-06410a1ace2e.png)

Please consider changing the colors to make it easy to detect changes.

**Comment by liviuschera** [comment]
Hi Amit. Thanks for your kind words. You are right, the diff colors are quite faded so I bumped up the luminosity. Let me please know if the change I made it's an improvement.

Cheers.

**Comment by amithegde** [comment]
This is perfect! Thanks✌👌👍
