### ISSUE TITLE
Improve code documentation coloring on the diff view for Noctis Azureus 

### ISSUE THREAD

**Issue by amithegde** [liviuschera/noctis#28]
Further, I noticed it's hard to read the documentation comments. Here is an example:

![image](https://user-images.githubusercontent.com/816051/63727188-615e9380-c814-11e9-90c3-7554077e1616.png)

It's a C# file it that matters. Please consider bumping the color!

**Comment by liviuschera** [comment]
Good catch mate. This time I decided to dial down the diff's color luminosity and to slightly increase the luminosity for comments. Please let me know how this suits you.

Cheers!

**Comment by amithegde** [comment]
> Good catch mate. This time I decided to dial down the diff's color luminosity and to slightly increase the luminosity for comments. Please let me know how this suits you.
> 
> Cheers!

This looks great✌👍👍👌😎😎
