### ISSUE TITLE
Noctis Azureus Debug console selection color

### ISSUE THREAD

**Issue by amithegde** [liviuschera/noctis#29]
On the debug console, when a row is highlighted, selected text should get a different background color
Here I have selected `Access-Control-Allow-Credentials` but when the row is highlighted, can't see which part of the text is selected.
![image](https://user-images.githubusercontent.com/816051/66236676-fd977800-e6a7-11e9-8557-472140e9c574.png)

**Comment by liviuschera** [comment]
Hey mate, thanks for helping to improve the theme. I really appreciated it.

I fiddle with the colors and it should look OK. Let me know what you think of it.

Cheers!
