### ISSUE TITLE
Occurrences Highlight not visible in Bordo

### ISSUE THREAD

**Issue by SimSmith** [liviuschera/noctis#30]
There is a default setting in VS Code called _Occurrences Highlight_ that will highlight all occurrences of a word when the caret is touching it. This highlighting is not visible in _Noctis Bordo_, but it works with all other themes.

**Comment by liviuschera** [comment]
Thanks for pointing this issue. I should be fixed now. Let me know if it's OK for you.

Cheers!

**Comment by SimSmith** [comment]
Yes, it looks good, cheers!
