### ISSUE TITLE
Noctis overrides Markdown diff code block styling

### ISSUE THREAD

**Issue by zachvalenta** [liviuschera/noctis#31]
Noctis seems like it *might* be overriding VS Code's default syntax highlight for Markdown `diff` code blocks. 

Example screenshots and a bit more explanation [here](https://github.com/microsoft/vscode/issues/83683).

**Comment by zachvalenta** [comment]
Also, keep up the good work! I've been using Noctis for almost a year now and really liking it.

**Comment by liviuschera** [comment]
Hi mate! 
Thanks for the feedback. I really appreciate it. 😊

In regards to the issue you raised, as you can see in the attached screenshots, everything works just fine for me.

![src dif](https://user-images.githubusercontent.com/12068956/68273749-d3721500-00ae-11ea-9195-7bf860dc6d03.png)


![prev diff](https://user-images.githubusercontent.com/12068956/68273759-dbca5000-00ae-11ea-9d8c-f84b2333825b.png)


The only thing that comes to mind is that you maybe you modified the indentation as apparently vscode is sensitive to it. I have noticed that if I add a space in front of `+` or `-` the `diff` highlight will not work anymore in the preview. 

Please let me know if playing with indentation helped.

Cheers!

**Comment by zachvalenta** [comment]
Just to clarify: I'm talking about the syntax highlight in the normal editor mode, not the preview. 

I can see the diff highlight in the preview, but we should also see it in the editor as well, like this https://github.com/microsoft/vscode/issues/83683#issuecomment-548159182. Right now I can only see the diff highlighting in the editor w/ Noctis disabled.

**Comment by liviuschera** [comment]
Done. I just had to add syntax highlighting for the inserted and deleted diff code.

Please let me know if i's OK for you.

**Comment by zachvalenta** [comment]
Really good stuff, and much appreciated :) 👍🏼
