### ISSUE TITLE
Search result highlight color on Noctis Azureus needs change

### ISSUE THREAD

**Issue by amithegde** [liviuschera/noctis#32]
Looking at an SCSS file and search result highlight looks like this:

![image](https://user-images.githubusercontent.com/816051/68525265-bd1db200-0284-11ea-9300-4fa4fec9a5d1.png)

Makes it hard to read. Please change the color tint.

**Comment by liviuschera** [comment]
I changed it in all dark theme variants. 
I hope it's OK for you too. 

Cheers!
