### ISSUE TITLE
REQUEST: What dose source.go mean in scope of textMateRules

### ISSUE THREAD

**Issue by LiangXianSen** [liviuschera/noctis#36]
Noctis is really nice and beautiful. I use it in vscode. I wanna change some colors of codes in golang. I found `source.go` in settings.json can influence specific types of golang displays. But struct declarations are no exactly handling.

What can I do could it display the color I expect.

**Comment by liviuschera** [comment]
Thanks for your feedback mate. 
I'm not really sure what is what your are asking. Could you, please, provide some code samples and start from there?

Cheers!

**Comment by LiangXianSen** [comment]
I found `source.go` in settings.json of vscode like :
```
{
    "scope": "source.go keyword",
    "settings": {
        "foreground": "#xxxxx"
    }
}
```

I'm not sure that source.go is not defined by official right?  I mean I wanna know what `source.go` affect here. Could I add more rules for displays golang code with the color i expect.

**Comment by liviuschera** [comment]
Go lang syntax is supported out of the box by VS Code and you can inspect the colour tokens by using `Developer: Inspect TM Scopes` command which can be activated by pressing `CTRL + SHIFT + P` on Windows and `COMMAND + SHIFT + P` on MacOS.

I'm not sure if this answers your questions, but here you can find more info that might more pertinent to what you are looking: [How to get access to Developer: Inspect TM Scopes data? [duplicate]
](https://stackoverflow.com/questions/51523436/how-to-get-access-to-developer-inspect-tm-scopes-data?noredirect=1)
