### ISSUE TITLE
Syntax Highlighting for each language...

### ISSUE THREAD

**Issue by rediffusion** [liviuschera/noctis#37]
## About Syntax.

 First of all th10 for an awesome theme! 🎆
I don't understand why the color syntax for all languages that I use (i.e. - C#, JS, TS, AHK, C++, C, Java, Html, CSS, Python...) is the same?
 Is there a wat to implement for ich language his own different ⚡`Syntax Highlighting`⚡ ?

Regards! 👍✌️

**Comment by liviuschera** [comment]
Thanks for your kind words.

Would you please elaborate on your question, maybe coming up with some code examples pointing out how would you like the code to look like?

Cheers!

**Comment by rediffusion** [comment]
0Key, my friend let me explain it another way...

As an example, I'll take the IDE called «[NotePad++](https://notepad-plus-plus.org/downloads/)».
I have a theme called "Plastic Code Wrap". It looks like this:

![image](https://user-images.githubusercontent.com/30071027/71870673-e2fdf080-3127-11ea-8c28-428853d86fee.png)

Now I put here some `code`, then I switch to other languages...

## C#

![image](https://user-images.githubusercontent.com/30071027/71870861-5a338480-3128-11ea-8f6e-cd5d191ade4f.png)

## JavaScript

![image](https://user-images.githubusercontent.com/30071027/71870894-79321680-3128-11ea-83cb-26d711905f0b.png)

## AutoHotkey

![image](https://user-images.githubusercontent.com/30071027/71870922-94048b00-3128-11ea-9bb0-88cf003a5864.png)

## C++

![image](https://user-images.githubusercontent.com/30071027/71870945-a8e11e80-3128-11ea-8b35-b84e162f0b6f.png)

## CSS

![image](https://user-images.githubusercontent.com/30071027/71870978-c57d5680-3128-11ea-9c90-c90aa3fe5a69.png)

## HTML 

![image](https://user-images.githubusercontent.com/30071027/71870995-d29a4580-3128-11ea-864e-8311edc3ce87.png)

Different syntax, color, style, font, weight, brackets... etc.
But in your cool **theme** I see the same shit with all languages. Please help! 🙏

**Comment by liviuschera** [comment]
Can you accomplish the above results (or similar) by using VS Code text editor with different theme?

Since I'm not familiar with Notepad++ I'll have to assume that in order to get different syntax colouring you changed the language mode. If that's the case you can get a similar result in VS Code via `⌘ + K + M` in MacOS or `CTRL  + K + M` in Windows.
