### ISSUE TITLE
Italic for `type` in `import type`

### ISSUE THREAD

**Issue by JacksonKearl** [liviuschera/noctis#38]
Issue Type: <b>Bug</b>

Currently there are `keyword.control.import { "fontStyle": "italic" }` and `keyword.control.from { "fontStyle": "italic" }`, it would be nice to also have `keyword.control.type { "fontStyle": "italic" }` for the new `import type` syntax in TS3.8. I could configure in `"editor.tokenColorCustomizations"`, but that's not ideal as I'd need a seperate entry for each variant. 

I'm on the VS Code team and I love the theme btw!

Extension version: 10.24.0
VS Code version: Code - Insiders 1.42.0-insider (33c79d5ad447956814a2a3658029dffb9e28bae6, 2020-01-15T08:53:57.100Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (6.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by liviuschera** [comment]
Apparently VS Code Typescript grammar is not yet updated so it cannot pick up `keyword.control.type` token. Any advice regarding this issue?

Thanks for the feedback mate.

**Comment by JacksonKearl** [comment]
If you go on the latest Insiders and use TS 3.8.0-beta, you should be able to see them:

![image](https://user-images.githubusercontent.com/8586769/72636895-f4f44600-3914-11ea-8101-d33b8f741956.png)


Alternatively, you could just apply it for `meta.import`, as that seems to be the intent?

**Comment by liviuschera** [comment]
Done. Happy hacking mate!
