### ISSUE TITLE
iTerm theme

### ISSUE THREAD

**Issue by sagar-gavhane** [liviuschera/noctis#40]
Hi @liviuschera,

This is one of the awesome 👍🏻 vscode theme I've ever seen 👀 in my life. I want one more favor to make Notics iTem theme.

I'm ready to contribute to this.

Thanks a lot.

**Comment by sagar-gavhane** [comment]
Hey, 

Quick update.

I'm started working on Noctis iTerm and created basic Noctis iTerm theme here: https://gist.github.com/sagar-gavhane/a1ea70faacfb957a14e512d1799db81f

Please provide your valuable feedback 😊.

**Comment by liviuschera** [comment]
Hi mate, thanks for your kind words.
I would love to provide some feedback unfortunately I do not own a Mac. I think that, for now, some screenshots would do the trick. 
Alternatively you might want to have a look over @ethanfann's work [#11](https://github.com/liviuschera/noctis/pull/11). I do think that he did a terrific job with Alfred and iTerm2 versions. Maybe a collaboration would help speeding out the process. 

Cheers!

**Comment by sagar-gavhane** [comment]
@liviuschera agree with you @ethanfann done great work.
