### ISSUE TITLE
Maybe dim the green string a little bit? Thanks:D

### ISSUE THREAD

**Issue by bao007fei** [liviuschera/noctis#42]
IMO, it's a little bit brighter than other elements.

![image](https://user-images.githubusercontent.com/24863266/76654905-0d947b80-65a7-11ea-994f-6152c0e2a979.png)

**Comment by liviuschera** [comment]
Thanks for reaching out. I feel that  the green I used for string makes it pop out in the right way without being obtrusive and complements nicely the other ones in the theme. So and for the time being I'm quite happy with the brighter green.

Cheers mate!
