### ISSUE TITLE
Noctis Lux, more contrast for orange text?

### ISSUE THREAD

**Issue by mikl** [liviuschera/noctis#46]
First of all, thanks for making this, great work.

However, if I may propose one thing, a little more contrast for the orange text on “Noctis Lux”.

When editing a Shell Script, like pictured below, all shell commands get colored orange, and on an orange background, that gets more than a little hard to read in my opinion. I think this could be helped, if the orange was just a little darker, so it would stand out from the background.

<img width="538" alt="Screenshot 2020-09-28 at 22 46 00@2x" src="https://user-images.githubusercontent.com/10263/94484427-b2417800-01dc-11eb-9ac5-f7ddc4edd69e.png">

**Comment by liviuschera** [comment]
Hi there,

I have bumped up the contrast for orange and in the process I have toned down the workbench colors for both Lux and Lilac variations. Please give it a spin and please let me know what you think.

Cheers!

**Comment by mikl** [comment]
That is definitely better, thank you.
