### ISSUE TITLE
name of the font for the examples

### ISSUE THREAD

**Issue by fegonzaleza** [liviuschera/noctis#49]
Hi, i want to know the name of the font you used for the image in examples! its really cool!

**Comment by nivv** [comment]
@fegonzaleza The font used in screenshots is called Cartograph CF

![Skärmavbild 2020-10-27 kl  12 54 39](https://user-images.githubusercontent.com/4033930/97298457-b4d2d400-1853-11eb-9c99-b73755e1ebc8.png)
