### ISSUE TITLE
Uva color schema suggestions

### ISSUE THREAD

**Issue by ovidius72** [liviuschera/noctis#5]
Hi. Thanks for this wonderful theme. It looks really amazing.

I'be been trying the new color scheme, Uva, and it  looks very nice as well.
The only issue I've found so far is about the suggestion popup.

As you can see from the image, it's hard to distinguish which item is highlighted at first sight. 

![personalmessagesubscriber_ts_ _react-tsx](https://user-images.githubusercontent.com/3592928/48414993-7027fe00-e74c-11e8-8d34-701c460c9fe9.png)

It would be better to have it a bit darker.
Thanks.

**Comment by liviuschera** [comment]
Hi Antonio,

Thanks for the spot on catch.

The issue should be fixed in the new version I just released. I would love to hear back from you after you give it a spin.

Cheers!

**Comment by liviuschera** [comment]
I’m glad you like it mate! Enjoy!
