### ISSUE TITLE
Current extensionKind definition is too restrictive

### ISSUE THREAD

**Issue by bamurtaugh** [liviuschera/noctis#54]
Hi! I'm from the VS Code team and have tested whether Noctis can run in the different extension host setups VS Code currently supports. I've found that the current definition of `extensionKind` for your extension is too restrictive.

The extension has the `extensionKind` set to `["ui"]`: https://github.com/liviuschera/noctis/blob/master/package.json#L11.

This defines that the extension can only run in the VS Code desktop extension host. However, this extension can also run on the workspace extension host (which is used for remote scenarios).

Thus, the best practice would be to change the extensionKind to `["ui", "workspace"]`.

We have a way to customize the extensionKind from an extension in the VS Code core. Given the popularity of your extension I will do this in the meantime. 

Please let me know if you have any questions - I'm happy to help clarify anything. Thank you!

**Comment by liviuschera** [comment]
Hey there! Thanks for reaching out.

Should I modify `extensionKind ` to `["ui", "workspace"]`?

Cheers!

**Comment by bamurtaugh** [comment]
Yes, we'd recommend modifying to `["ui", "workspace"]`.

There's more information in the section [here](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location). 

Updating to `"extensionKind": ["ui", "workspace"]` indicates the extension prefers to run as a UI extension, but does not have any hard requirements on local assets, devices, or capabilities. When using VS Code, the extension will run in VS Code's local extension host if it exists locally, otherwise will run in VS Code's workspace extension host if it exists there. This will also allow your extension to work in the Codespaces browser-based editor (it will run in the remote extension host always when in the browser as no local extension host is available there).

Please let me know if you have any other questions!

**Comment by liviuschera** [comment]
Sure, no worries.

I've pushed the change and it should be up and running.

Hope it'll fix it. 

Cheers!

**Comment by bamurtaugh** [comment]
Fantastic, thank you for the quick response! 🚀 I'll close out this issue.

**Comment by idan** [comment]
@bamurtaugh hey — do you happen to know what the extension needs to specify for `extensionKind` so that it works in vscode.dev / github.dev? TS suggests a third kind of `extensionKind` option, `web`, in addition to `ui` and `workspace`. I've tried overriding the extension kind using various permutations, but so far no joy installing this extension vscode.dev:

```
    "remote.extensionKind": {
        "liviuschera.noctis": ["web", "ui", "workspace"]
    }
```

Interestingly, [other theme extensions that do not specify `extensionKind` at all](https://github.com/theacodes/witchhazel/blob/master/package.json) install just fine.

**Comment by Russ716** [comment]
Hallo! I've got the Cartograph font, because I want the shifting "cursive" semantic formatting as well as these fantastic colors (#TeamAzure!). Unfortunately, I've hit a roadblock. Any chance you can help a new developer out?
