### ISSUE TITLE
The color used for markdown fenced blocks is too dim

### ISSUE THREAD

**Issue by memeplex** [liviuschera/noctis#63]
Fenced blocks have many roles in markdown:
1. verbatim text
2. code blocks
3. a generalization of the above in pandoc 
4. a translation of reStructuredText roles in MyST markdown
5. probably many others

Most Noctis themes treat these blocks almost as comments, in that they are shown in a dimmed down fashion, except when a language is specified (then the syntax highlighting for the language is used, of course). But there is no reason to assume that these blocks are less important than other contents or shouldn't divert attention as much as other contents.  This assumption is unsafe even for the vanilla verbatim block.

I think that deemphasizing these blocks is an undesirable quirk of the Noctis themes.

![image](https://user-images.githubusercontent.com/2845433/139573577-406c977c-0f82-4cbe-ac28-09ad7e657760.png)

**Comment by liviuschera** [comment]
Hi, this should have been fixed. Please let me know if that's the case.
