### ISSUE TITLE
Font Not Showing

### ISSUE THREAD

**Issue by c0mm0dore** [liviuschera/noctis#64]
I've just installed your Theme (which I like) but the _Cartograph CF_ font that you used is not showing (I have it on my PC). How Can I solve this?
I've attached you a screenshot.
![immagine](https://user-images.githubusercontent.com/31392205/144745992-2f8a80e2-c588-4fd1-9adc-6c16232cb4c0.png)

Thanks

**Comment by linqingyao** [comment]
@c0mm0dore Hey, man! I had the same problem. Can you tell me how you complete the font display?
