### ISSUE TITLE
Support for Markdown strikethrough

### ISSUE THREAD

**Issue by h-h-h-h** [liviuschera/noctis#69]
I don't understand the relationship between between VS Code and this extension. But VS Code just [added support](https://github.com/microsoft/vscode/issues/43504) for rendering `~~strikethrough text~~` in Markdown files differently in the editor. However, with your theme "Noctis Bordo", it currently isn't rendered any different.

Since your read-me lists Markdown as a supported language, is there anything you can do about that, so that strikethrough text is rendered differently -- I'd imagine with ~~strikethrough effect~~?

**Comment by liviuschera** [comment]
Hi, this should have been fixed. Please let me know if that's the case.

**Comment by h-h-h-h** [comment]
The whole `~~strikethrough text~~` now has a strikethrough effect. However, the rendering differs from `*italic*` and `**bold**` text. For italic and bold, the asterisks making the text italic or bold are also italic or bold, respectively. *But* they're also gray! So, `~~` to the left and to the right should follow that pattern and be gray.

But since strikethrough interferes with the text, I think it would be best to omit the strikethrough effect for `~~`. Without strikethrough effect, it's like a continuation of the strikethrough, anyway.

The strikethrough line is also a bit thick. Is there a way to make it thinner? You should be able to quite easily read the text, while still quickly and intuitively understanding that there's strikethrough markup. If it's impossible, it's okay.

**Comment by liviuschera** [comment]
I grayed out tilde character and removed "Cinnabar" color from the strike-through text. I think this should make it more readable. There is no way, as far as I know, to fiddle with the strike-through line, so I'll leave it as is.

**Comment by h-h-h-h** [comment]
Okay. Then let's close this. Thank you!
