### ISSUE TITLE
Obscuro doensn't have visible divider when there are multiple panels

### ISSUE THREAD

**Issue by bin-wang** [liviuschera/noctis#79]
I just noticed that when you split the editor to create multiple panels, Obscuro is the only variant that doesn't have a divider between those panels. Is this intended? See the comparison below between Obscuro and Sereno.

Obscuro:
![Obscuro](https://github.com/liviuschera/noctis/assets/25761459/655dba8b-bb76-4827-804b-e449544465db)

Sereno:
![Sereno](https://github.com/liviuschera/noctis/assets/25761459/f953d23f-da10-4677-a4e7-4564b310a710)

**Comment by liviuschera** [comment]
It should be fixed now.

**Comment by bin-wang** [comment]
Thanks for the fix. Love your work!
