### ISSUE TITLE
Noctis UVA variant option is not visible to select in macOS High Sierra Version 10.13.6

### ISSUE THREAD

**Issue by afiqhamzah** [liviuschera/noctis#9]
OS : macOS High Sierra Version 10.13.6

VS Code version : Version 1.27.2 (1.27.2)

![image](https://user-images.githubusercontent.com/26989296/50952622-eeeeac80-14eb-11e9-8459-2565e4e50567.png)

**Comment by liviuschera** [comment]
Hi mate. Thanks for the details.

I see that the you VS Code version is 1.27.2. Please update your editor to the latest version: 1.30.2. Noctis theme requires at least v1.29.0 

If the problem still persists after you have updated:
1. install [Visual Studio Code Insiders](https://code.visualstudio.com/insiders)
2. install Noctis in the VSCode Insiders

Please let me know if it helps.

**Comment by afiqhamzah** [comment]
Thanks, it works now

Tried updating the version but none avail, I'd installed a fresh VS Code and the UVA theme variant finally worked

**Comment by liviuschera** [comment]
I'm happy it turned out OK. Thank you for the update mate.
